### ISSUE TITLE
translocation_survival_analysis.Rmd: Revise conditional effects plots

### ISSUE THREAD

**Issue by rolandknapp** [SNARL1/translocation#10]
- Use unstandardized values on plot axes. 
- Replace lines with mean line and uncertainty band?

**Comment by mqwilber** [comment]
@mqwilber, insert new R chunk with some guidance on how do to this.

**Comment by rolandknapp** [comment]
@mqwilber During our 2-Nov meeting, let's discuss whether these revised conditional effects plots (using unstandardized data) should be included in the manuscript or the supplement, and whether to replace lines with mean line and uncertainty band.

**Comment by mqwilber** [comment]
@mqwilber go into code and show how we can compute the uncertainty bands.

**Comment by rolandknapp** [comment]
I revised the plots using Mark's code.
