### ISSUE TITLE
Viability analysis: Review the criteria we used to include/exclude populations

### ISSUE THREAD

**Issue by rolandknapp** [SNARL1/translocation#15]
In the Methods, mention that only a subset of translocated populations were included in the viability analysis, i.e., those with relatively high survival following translocation. We need to review how this decision was made to ensure that is still reasonable.

**Comment by mqwilber** [comment]
@mqwilber, add in viability analysis for all translocated populations. Update Figure 1 to reflect this.

**Comment by mqwilber** [comment]
Updated viability analysis to include all twelve translocated populations in d60cb23c.
