### ISSUE TITLE
If needed, add more details to Table 1 for source of parameter values

### ISSUE THREAD

**Issue by mqwilber** [SNARL1/translocation#24]
@rolandknapp, I have added a table with baseline parameter values for the population viability model and sources for these parameter values in commit 922068731.  Could you look over the [column "Source"](https://github.com/SNARL1/translocation/blob/922068731e76f46256cf648370cf983b54e6c6ff/doc/manuscript/translocation.qmd#L334)? I very generally said "Estimated from field data, observations, natural history knowledge" for many of the parameters. We should discuss if we want to be more specific on how these estimates were generated, either in the table or elsewhere in the supplementary material.

**Comment by rolandknapp** [comment]
@mqwilber, To document how year-1 subadult survival and year-1 tadpole survival were estimated, I added my calculations to `translocation_survival_analysis_suppl.Rmd`. I don't know that we need to add any additional information to the table, but we should probably indicate in a footnote or elsewhere that we generally used parameter values from Briggs et al. (2005), but updated some values based on new data (provided in above file).
