### ISSUE TITLE
Create makefile for CMR and viability analyses

### ISSUE THREAD

**Issue by rolandknapp** [SNARL1/translocation#26]

**Comment by mqwilber** [comment]
@rolandknapp, in commit 94532a63 and branch `makefile`, I have built a makefile that includes the dependencies and targets of the population viability analysis. 

To recreate the population viability analysis results, you *should* be able to 

1. Pull the branch `makefile`
2. cd into the root directory of the Repo
3. Run `make install_packages` in the terminal
4. Run `make` in the terminal

The full viability analysis takes ~30 minutes on my machine.  It would be useful to see if the analyses work on your machine and what errors occur (given that you are going to have a different R version and environment).

**Comment by rolandknapp** [comment]
@mqwilber Running install_packages resulted in a few errors. I think I could resolve some of these by installing what appear to be some missing Linux packages, but I thought it might be useful for you to review the `make install_packages` log first because that might lead you to make some revisions to the install_packages script. I've attached the log below. Let me know how you'd like to proceed. [makefile_log.txt](https://github.com/SNARL1/translocation/files/10889798/makefile_log.txt)

**Comment by mqwilber** [comment]
Thanks for giving this a try @rolandknapp.  It looks like it is an error coming from installing `devtools`.  Here are two candidate solutions.

1. First, try installing the following Linux packages in your terminal `sudo apt-get install libharfbuzz-dev libfribidi-dev` and re-running `make install_packages`.
2. If this doesn't work I will try debugging in a Linux VM.  But I'd recommend opening [`code/install_R_packages.R`](https://github.com/SNARL1/translocation/blob/makefile/code/install_R_packages.R), starting an R instance, and loading each of the listed R packages separately.  Let's see if they all load and which give errors.  If they all load, then try running `make` and let's see what happens on your machine.

This also might be a sign for us to use Docker or a conda environment to ensure portability of the analyses between machines.

**Comment by rolandknapp** [comment]
@mqwilber I installed those two system packages, and a couple of additional packages that were dependencies. That seems to have worked and allowed the installation of nearly all R packages. The one exception was `RcppEigen` Installing the `gfortran` system package allowed installation of `RccpEigen`. So, all packages were installed successfully. 

I then ran `Make` and it error-ed pretty quickly with the following: 

> cd code; \
Rscript extract_survival_estimates.R; \
cd ..
── Attaching packages 
Working on lake 70414 
Error in gzfile(file, "rb") : cannot open the connection
Calls: readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/Users/mqwilber/Repos/cmr-analysis/out/model/70414_model.rds', probable reason 'No such file or directory'
Execution halted

I'm not sure why the absolute path to a directory on your computer is used (mqwilber/Repos/cmr-analysis) instead of a relative path to cmr-analysis/, but I suspect that you can figure this out relatively easily. I can confirm that the cmr-analysis and translocation repos are both located in my data/ directory.

**Comment by mqwilber** [comment]
@rolandknapp, that was my fault.  I left an absolute path in there.  Just pushed an update at 5f44062b.

**Comment by rolandknapp** [comment]
`make` error-ed out. I need to jump on a call but here is the log:

> Rscript extract_survival_estimates.R; \
cd ..
This is cmdstanr version 0.5.3
- CmdStanR documentation and vignettes: mc-stan.org/cmdstanr
- CmdStan path: /home/roland/.cmdstan/cmdstan-2.31.0
- CmdStan version: 2.31.0
── Attaching packages ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse 1.3.1 ──
✔ ggplot2 3.4.1     ✔ purrr   0.3.4
✔ tibble  3.2.0     ✔ dplyr   1.0.9
✔ tidyr   1.2.0     ✔ stringr 1.4.0
✔ readr   2.1.2     ✔ forcats 0.5.1
── Conflicts ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::between()   masks data.table::between()
✖ tidyr::extract()   masks magrittr::extract()
✖ dplyr::filter()    masks stats::filter()
✖ dplyr::first()     masks data.table::first()
✖ dplyr::lag()       masks stats::lag()
✖ dplyr::last()      masks data.table::last()
✖ purrr::set_names() masks magrittr::set_names()
✖ purrr::transpose() masks data.table::transpose()
Working on lake 70414 
Error in gzfile(file, "rb") : cannot open the connection
Calls: readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '../cmr-analysis/out/model/70414_model.rds', probable reason 'No such file or directory'
Execution halted
cd code; \
Rscript extract_survival_estimates.R; \
cd ..
This is cmdstanr version 0.5.3
- CmdStanR documentation and vignettes: mc-stan.org/cmdstanr
- CmdStan path: /home/roland/.cmdstan/cmdstan-2.31.0
- CmdStan version: 2.31.0
── Attaching packages ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse 1.3.1 ──
✔ ggplot2 3.4.1     ✔ purrr   0.3.4
✔ tibble  3.2.0     ✔ dplyr   1.0.9
✔ tidyr   1.2.0     ✔ stringr 1.4.0
✔ readr   2.1.2     ✔ forcats 0.5.1
── Conflicts ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::between()   masks data.table::between()
✖ tidyr::extract()   masks magrittr::extract()
✖ dplyr::filter()    masks stats::filter()
✖ dplyr::first()     masks data.table::first()
✖ dplyr::lag()       masks stats::lag()
✖ dplyr::last()      masks data.table::last()
✖ purrr::set_names() masks magrittr::set_names()
✖ purrr::transpose() masks data.table::transpose()
Working on lake 70414 
Error in gzfile(file, "rb") : cannot open the connection
Calls: readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '../cmr-analysis/out/model/70414_model.rds', probable reason 'No such file or directory'
Execution halted
cd code; \
Rscript extract_abundance_trajectories.R; \
cd ..
This is cmdstanr version 0.5.3
- CmdStanR documentation and vignettes: mc-stan.org/cmdstanr
- CmdStan path: /home/roland/.cmdstan/cmdstan-2.31.0
- CmdStan version: 2.31.0
── Attaching packages ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse 1.3.1 ──
✔ ggplot2 3.4.1     ✔ purrr   0.3.4
✔ tibble  3.2.0     ✔ dplyr   1.0.9
✔ tidyr   1.2.0     ✔ stringr 1.4.0
✔ readr   2.1.2     ✔ forcats 0.5.1
── Conflicts ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::between()   masks data.table::between()
✖ tidyr::extract()   masks magrittr::extract()
✖ dplyr::filter()    masks stats::filter()
✖ dplyr::first()     masks data.table::first()
✖ dplyr::lag()       masks stats::lag()
✖ dplyr::last()      masks data.table::last()
✖ purrr::set_names() masks magrittr::set_names()
✖ purrr::transpose() masks data.table::transpose()
Working on lake 70414 
INFO: Assuming cmr-analysis folder is stored in the same directory as translocation folder 
Working on lake 70370 
INFO: Assuming cmr-analysis folder is stored in the same directory as translocation folder 
Working on lake 70134 
INFO: Assuming cmr-analysis folder is stored in the same directory as translocation folder 
Working on lake 70505 
INFO: Assuming cmr-analysis folder is stored in the same directory as translocation folder 
Working on lake 70550 
INFO: Assuming cmr-analysis folder is stored in the same directory as translocation folder 
Working on lake 70641 
INFO: Assuming cmr-analysis folder is stored in the same directory as translocation folder 
Working on lake 70619 
INFO: Assuming cmr-analysis folder is stored in the same directory as translocation folder 
Working on lake 70449 
INFO: Assuming cmr-analysis folder is stored in the same directory as translocation folder 
Working on lake 70413 
INFO: Assuming cmr-analysis folder is stored in the same directory as translocation folder 
Working on lake 70628 
INFO: Assuming cmr-analysis folder is stored in the same directory as translocation folder 
Working on lake 70556 
INFO: Assuming cmr-analysis folder is stored in the same directory as translocation folder 
Working on lake 74976 
INFO: Assuming cmr-analysis folder is stored in the same directory as translocation folder 
cd code; \
Rscript extinction_and_growth_rate_analysis.R; \
cd ..
── Attaching packages ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse 1.3.1 ──
✔ ggplot2 3.4.1     ✔ purrr   0.3.4
✔ tibble  3.2.0     ✔ dplyr   1.0.9
✔ tidyr   1.2.0     ✔ stringr 1.4.0
✔ readr   2.1.2     ✔ forcats 0.5.1
── Conflicts ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::between()   masks data.table::between()
✖ dplyr::filter()    masks stats::filter()
✖ dplyr::first()     masks data.table::first()
✖ dplyr::lag()       masks stats::lag()
✖ dplyr::last()      masks data.table::last()
✖ purrr::transpose() masks data.table::transpose()
Warning message:
In melt.data.table(data.table(mus), variable.name = "lake_id", value.name = "surv_est") :
  id.vars and measure.vars are internally guessed when both are 'NULL'. All non-numeric/integer/logical type columns are considered id.vars, which in this case are columns []. Consider providing at least one of 'id' or 'measure' vars in future.
Error in fread(file.path("..", "out", "yearly_survival_estimates_all_individuals.csv")) : 
  File '../out/yearly_survival_estimates_all_individuals.csv' does not exist or is non-readable. getwd()=='/media/roland/data/translocation/code'
Execution halted

**Comment by mqwilber** [comment]
@rolandknapp, I think this will be easier to debug over a call.  The errors are due to directory structure.  We need to compare directory structures and see where you are running the makefile from.  I could meet after 3:30 ET my time today if you are available.

**Comment by rolandknapp** [comment]
@mqwilber Agreed. Let's meet at 3:30 ET today on my Zoom link. See you then.

**Comment by mqwilber** [comment]
@mqwilber,  update cmr dependencies in makefile based on new folder structure.

**Comment by rolandknapp** [comment]
@mqwilber The revised translocation `Makefile` runs largely as expected except for one remaining glitch. When `translocation_survival_analysis.R` completes, it issues this error: 
> Error while shutting down parallel: unable to terminate some child processes

I'm guessing that this error (which does not crash the run) terminates the `make` process before the final line in the associated rule runs: `rm -f code/translocation_survival_analysis.R`. As a result, the `.R` file is not removed. 

Here are some things that I learned about the error. 

- The error message does not appear when running `translocation_survival_analysis.R` in the R Studio source window (instead of in Terminal, via  the `Makefile`). 
- The error may be the result of a bug in the `processx` R package, although based on information about the bug [here](https://blog.r-hub.io/2020/02/20/processx-blocked-sigchld/), I suspect that the bug was fixed quite a while ago.  

How to proceed? Sorry to drag you down another rabbit hole.

**Comment by rolandknapp** [comment]
@mqwilber Regarding the parallel-related issue described in my previous comment, the issue seems to only affect the removal of  `translocation_survival_analysis.R` and `translocation_survival_analysis_supp.R` when the runs of those scripts complete. The remainder of the translocation Makefile runs as expected. As such, the issue described is relatively trivial and the translocation Makefile is ready to merge with the viability Makefile.

**Comment by mqwilber** [comment]
477d8fc closes this issue
