### ISSUE TITLE
Add "year" predictor variable to 1-year survival model

### ISSUE THREAD

**Issue by rolandknapp** [SNARL1/translocation#28]
Inclusion of "year" as a predictor variable would be useful in our description of the viability results. Specifically, if "year" is an important predictor of 1-year frog survival, it would highlight the fact that recent translocations are more likely to have produced populations with low extinction probability.

**Comment by rolandknapp** [comment]
@mqwilber I reran the models with "year" included as a predictor variable. In the model without a grouping variable (i.e., site_id or translocation_id), year is a significant (+) predictor of 1-year survival. However, in models with a grouping variable, the effect of year is no longer important. This isn't particularly surprising giving that the year and grouping variables are closely associated. Nonetheless, the model results don't give us an easy way to talk about the year effect in the manuscript. The revised analyses and the associated results in the "add_year" branch.

To gain the necessary insights another way, I tabulated whether translocations were "early" or "late" (< 2013 versus >= 2013) and resulted in a 50-year extinction probability (omega = 0.3) of 1.0 versus < 1. Based on this, 1/5 early translocations resulted in viable populations. In contrast, 5/7 late translocations resulted in viable populations. 

Let's discuss how to include these results in the manuscript.

**Comment by mqwilber** [comment]
I think we can close this issue. @rolandknapp, can you confirm?

**Comment by rolandknapp** [comment]
Confirmed.
