### ISSUE TITLE
Add section-specific bibliographies

### ISSUE THREAD

**Issue by rolandknapp** [SNARL1/translocation#29]
@mqwilber A description of how to create section-specific bibliographies is provided [here](https://github.com/pandoc-ext/section-bibliographies#quarto). This would allow us to create one bibliography for the main manuscript and another for the Supporting Information, as required by PNAS. Unfortunately, running the `quarto install extension pandoc-ext/section-bibliographies` in Terminal (from the translocation directory) throws the error "command 'quarto' not found". Let's figure this out.

**Comment by mqwilber** [comment]
The command is working for me.

**Comment by rolandknapp** [comment]
I will troubleshoot why it is not working for me. Assuming that I am able to install the extension, I will reformat the bibliography to create one for the manuscript and one for the Supporting Information.

**Comment by rolandknapp** [comment]
I was able to install the section-bibliographies extension (perhaps due to installing the latest version of Quarto). I updated the YAML as required to use this extension, but when I attempt to render the manuscript file I get the error, "Error running filter section-bibliographies: Could not find  executable section-bibliographies". I'm curious if you see the same error when you attempt to use the extension. FYI, the YAML is now as follows:

---
filters:
  - section-bibliographies
bibliography: translocation.bib
reference-section-title: References
citeproc: false
csl: pnas.csl
format: docx
editor: visual
---

**Comment by rolandknapp** [comment]
I now have the section-bibliographies extension working. It still has a few glitches, but it works largely as expected. A full description of the solution is provided [here](https://stackoverflow.com/questions/75632573/quarto-extension-installed-but-not-found-during-render). The solution is going to cause version control issues due to having to provide the absolute file path for the extension. As such, I removed the extension-specific code from the YAML for now. We can add it back in during the final stages of manuscript creation. These separate bibliographies will be helpful when we move chunks of text from the main body of the manuscript to the Supporting Information section.
