### ISSUE TITLE
Separate figure numbering in manuscript and supporting information

### ISSUE THREAD

**Issue by rolandknapp** [SNARL1/translocation#30]
@mqwilber I've been investigating this issue and have not found a good answer. Check out this [link](https://stackoverflow.com/questions/75445753/is-it-possible-to-reset-and-re-number-cross-references-to-figures-in-quarto-r), and the links within it. As an example of the journal templates that might provide some useful code, I looked at the PLOS template. Let's decide how to proceed on this.

**Comment by mqwilber** [comment]
@mqwilber will work on this for the latex conversion
