### ISSUE TITLE
Reminder that repository is public. Is this an issue for contributors or journals?

### ISSUE THREAD

**Issue by rolandknapp** [SNARL1/translocation#5]
When pushing to the repo, it is important to remember not to include any site-identifying information except site_id (e.g., site name, x-y coordinates). This will ensure that the provided information cannot be used to locate the site. Once that information is included in the repo, it is difficult to remove.

**Comment by mqwilber** [comment]
@rolandknapp and @mqwilber have looked at this, discussed and are ok with it.
