### ISSUE TITLE
Combine 2 analyses that identified predictors of post-translocation survival

### ISSUE THREAD

**Issue by rolandknapp** [SNARL1/translocation#54]
In the original submission, I conducted two analyses to describe post-translocation frog survival: 

1.  Relationship between survival of the first cohort translocated to a site and survival of subsequent translocated cohorts (Figure 3).
2.  Survival of translocated frogs as a function of climatic, habitat, and frog-specific characteristics (plus a site-level random effect; Figure 4). 

We agreed that the first of these analyses could be dropped and the importance of site in affecting survival (as indicated by Figure 3) could be described by a more thorough assessment of the importance of the site_id random effect in the second analysis. Decide how to modify this analysis to meet this objective.

**Comment by mbjoseph** [comment]
I agree we can generate a version of figure 3 that is not reliant on a separate model. Specifically, we can plot the predictions for each site from the main survival model (model `m1d`), which looks like it includes an effect of first introduction (at least, this is what the predictor `first` and its centered counterpart `first_c` appear to be). 

Am I interpreting `first` correctly as a binary indicator for whether the event was the first translocation cohort? 

If so, does it seem reasonable to generate a plot similar to Figure 3 (same axes, etc.), but showing the predictions from model `m1d`?

**Comment by rolandknapp** [comment]
You are interpreting the predictors, `first` and `transno`, correctly. I created the `first` column from the `transno` column to facilitate analysis 1 described above. 

Before you dive into making a new figure, I want to make sure I understand the issue we are trying to solve. The survival estimates for each translocation shown in figure 3 were obtained from site-specific mrmr models. These are the same survival estimates that I collated to create the response variable in analysis 2 described above (what you referred to as the "meta-analysis"). As such, why not show these estimates, as in Figure 3, drop analysis 1, and use the random effect from model 2 to tell us something about the importance of site shown in Figure 3? I realize that that is in fact the intent of behind your suggestion of generating predictions from the model. However, to me, plotting the actual survival estimates for each translocated cohort provides a more direct visualization of the importance of site than plotting predictors from the model. Can you help me to understand this issue? Sorry if I am being dense. 

If discussing this in a Zoom call would be more useful, I'm available all day Friday except 10-11 PST.

**Comment by mbjoseph** [comment]
Good idea - not being dense at all! Plotting the estimates of survival seems like a more direct path. 

How about this: I can draft a figure using the estimated individual-level survival probabilities with and without some model predictions, then we can evaluate what seems to get the point about site-level differences across most clearly.

**Comment by mbjoseph** [comment]
My understanding was Fig 3 shows cohort-level, rather than individual-level probabilities. But, we should probably sync up in real time to make sure we're synced up on this. I'll follow up via email for us to find a time.

**Comment by rolandknapp** [comment]
We agreed to drop the model related to Figure 3 and have the figure stand on its own.
