### ISSUE TITLE
Troubleshoot multibib extension

### ISSUE THREAD

**Issue by rolandknapp** [SNARL1/translocation#56]
I hate to take any more of your time, but I could use your help in troubleshooting an issue I am having with the `multibib` extension, an extension that allows the creation of separate bibliographies for different sections of a document (in our case, the main manuscript and the supporting information). I've described the issue [here](https://github.com/pandoc-ext/multibib/issues/11). Can you get multibib to work on your computer? I'm assuming that testing this would require only a few minutes. Thanks.

**Comment by mbjoseph** [comment]
Worked on this for a while to no avail. I have also tried splitting the supplement into a separate qmd file (similar to what I've done in the past with Rmd), but haven't been able to get the bibliographies to render properly in the main text and supplement.

**Comment by rolandknapp** [comment]
Thanks for trying. Did you have the same issue with the multibib.lua not recognized by Quarto? I had high hopes for this extension, but I guess for now we'll stick with one .qmd file containing all text, references, and figures. I hope that someone at Posit is working on a solution that will allow separate references for different sections.
