### ISSUE TITLE
Format figure 4 (results from viability analysis) to allow increased plot/font sizes

### ISSUE THREAD

**Issue by rolandknapp** [SNARL1/translocation#59]
Despite maximizing the size of this figure (while still keeping it within the left and right page margins) the figure panels and associated text is really small. This will need to be fixed before submission to PNAS, so I'm giving you a heads-up now. It may be possible to fix this simply by increasing the size of tick, axis, and legend labels, but I'm concerned that the plot sizes are sufficiently small that they won't get the attention they deserve (and may annoy reviewers trying to decipher them). One option may be to arrange the plots vertically (i.e., to fit in a single journal page column).

**Comment by mqwilber** [comment]
@rolandknapp, I increased the legend font sizes.  Hopefully that helps.  The vertical arrangement doesn't work as well as the horizontal arrangement in this case.

**Comment by rolandknapp** [comment]
@mqwilber, that's better, thanks. I also expaned the figure a bit into the right margin, so that helps too.
