### ISSUE TITLE
Roland's translocation analysis: Do we need to consider an analysis that is more focused on Bd?

### ISSUE THREAD

**Issue by rolandknapp** [SNARL1/translocation#6]
As we discussed during 12-Oct call, description of results from "drivers of frog survival" analysis likely needs to focus narrowly on Bd and specifically on the fact that Bd is not an important predictor of frog survival. Given that and limitations of the analysis, in which the Bd predictor variable is Bd load at time of translocation and post-translocation load is ignored, I'm wondering whether an analysis along the lines of Joseph and Knapp ([2018](https://esajournals.onlinelibrary.wiley.com/doi/full/10.1002/ecs2.2499)) is needed (to augment or replace current "drivers of frog survival analysis"). A possible alternative approach is to analyze Bd loads from before versus after translocation to see if they differ, if not perhaps the current simple analysis is sufficient. However, based on some data exploration that I did previously, I suspect that on average loads increased slightly following translocation.

**Comment by mqwilber** [comment]
@mqwilber, take a look Joseph and Knapp (2018) and see if these analyses are potentially doable for the new data.

**Comment by rolandknapp** [comment]
@rolandknapp, look at Bd load from before vs. after translocation. Also, Bd load vs. survival across individual years.

**Comment by rolandknapp** [comment]
Analysis of Bd load from before vs. after translocation indicates that [Bd load was higher after translocation](https://github.com/SNARL1/translocation/commit/37ae477202c454b02ff8d2111d2a3cf2c3434cd7). Comparison of Bd load vs. survival across all translocations is complicated due to large differences in numbers of frogs captured at each site following translocation and differences in the number of times individual frogs were captured. Those factors will produce lots of noise. In addition, distribution of Bd load is strongly left-skewed, so mean values (i.e., mean Bd load for a particular frog in years 0 and 1 following translocation) are not particularly informative.

**Comment by mqwilber** [comment]
Interesting results.  While Bd load is higher, I guess we come back to the question of whether it is biologically meaningful (i.e., meaningful for survival)? It looks like we are dealing with mean Bd loads of [before = 1626.843, after = 2166.777] with zeros included or [before = 5101.403, after = 6877.236] with zeros excluded.  Certainly, the variance around these means can lead to some meaningfully high loads for survival, but it visually looks like the variance is pretty similar between before and after.  We can discuss on Nov. 2, but perhaps a simple mark-recapture analysis (not the full fledged Joseph and Knapp analysis) could provide the necessary evidence regarding whether this shift is biologically meaningful.

**Comment by mqwilber** [comment]
Elaborating on the comment above. I think we could fit a simpler Cormack-Jolly-Seber model to the mark-recapture data from the translocated population to estimate how Bd load affects apparent survival following translocation.  Unlike Joseph and Knapp, we are not interested in the full population dynamics with this analysis so this simpler model should work and would be easier.   We could set this up in Stan or we could use Rmark.  The key challenges will be 

- Uneven sampling intervals.  
   - Rmark accounts for this or we can manually account for this by modeling a mortality rate with a time step $\Delta t$
-  Missing Bd loads
   - We can impute before fitting or impute during fitting
- Analyzing all lakes simultaneously
   - Conceptually this is not problem.  I wonder about computation time.  Might not be a problem.
- Developing the model
   - I think we could do this in Rmark, which could make development + fitting easy.  Developing in Stan would be straightforward, but would take a bit of time. Then we would need to consider fitting and analysis. 
   - Both would probably save us time relative to implementing the Joseph and Knapp model.

**Comment by rolandknapp** [comment]
Thanks for the follow-up. I like the suggested approach, but we should consider whether it is necessary. I'm sure it would be illuminating, but that is different from necessary. Let's discuss. 

In the analysis that you outline, key issues may be:
- A substantial number of frogs are never recaptured following translocation (especially at sites with low frog survival). Therefore, there are no Bd load data for these frogs and imputation would seem difficult. 
- Even for frogs that are recaptured, many are captured only a few times. Will this also affect the feasiblity/accuracy of Bd load imputation? 
- Max imputed the presence/absence of Bd infection. Does imputing Bd load pose any challenges?

**Comment by mqwilber** [comment]
@mqwilber and @rolandknapp will revisit as necessary, but decided that additional analysis is unnecessary based on the small effects and the ability to rely on previous results in Briggs et al. 2010 and Wilber et al. 2016 to make a compelling case that loads are not of an obvious concern.
